### ISSUE TITLE
Задание №1

### ISSUE THREAD

**Issue by TheGodfatherru** [TheGodfatherru/Elden-Ring-Planner#3]
Сейчас вам надо выучить 3 языка: JavaScript, HTML, CSS
JavaScript - https://www.youtube.com/playlist?list=PLM6XATa8CAG7DDIBjNVd78Fv5Ueo930IV
HTML/CSS - https://www.youtube.com/playlist?list=PLM6XATa8CAG4F9nAIYNS5oAiPotxwLFIr
Выбрать один курсов и к концу недели представить ваши успехи. В этих курсах он даёт задания, можете взять последнее вами просмотренное.

**Comment by Galaev-N** [comment]
![image](https://user-images.githubusercontent.com/96520174/212536253-9036c1ca-13cb-4a5d-bb00-b29bd58d837f.png)
![image](https://user-images.githubusercontent.com/96520174/212536282-af9b9aad-8f79-4d95-816d-26388f4be10c.png)
